### PR TITLE
Remove version printing

### PR DESCRIPTION
**Pull request by Ryanf55**
* It's on stderr and noisy
* Solves #70 

Logs are now clean (at least from MicroXRCEDDSGen)
```
$ colcon build --packages-up-to ardupilot_sitl
Starting >>> micro_ros_agent
--- stderr: micro_ros_agent                              
Cloning into 'xrceagent'...
Switched to a new branch 'ros2'
HEAD is now at c25243c Enable Domain Override on Reference and XML Participant (#351)
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (tinyxml2)
  does not match the name of the calling package (TinyXML2).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindTinyXML2.cmake:40 (find_package_handle_standard_args)
  /opt/ros/humble/share/fastrtps/cmake/fastrtps-config.cmake:51 (find_package)
  CMakeLists.txt:153 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

---
Finished <<< micro_ros_agent [4.49s]
Starting >>> ardupilot_sitl
Finished <<< ardupilot_sitl [2.99s]                  

Summary: 2 packages finished [8.21s]
  1 package had stderr output: micro_ros_agent
  ```

### CODE REVIEW

**Comment by pablogs9** [comment]
Please remove also https://github.com/eProsima/Micro-XRCE-DDS-Gen/blob/b4190682216992eaf1f9b99fc4b54a21c72847ff/scripts/microxrceddsgen.bat#L19 and https://github.com/eProsima/Micro-XRCE-DDS-Gen/blob/b4190682216992eaf1f9b99fc4b54a21c72847ff/scripts/microxrceddsgen.in#L7

**Comment by Ryanf55** [comment]
> Please remove also
> 
> https://github.com/eProsima/Micro-XRCE-DDS-Gen/blob/b4190682216992eaf1f9b99fc4b54a21c72847ff/scripts/microxrceddsgen.bat#L19
> 
> and
> https://github.com/eProsima/Micro-XRCE-DDS-Gen/blob/b4190682216992eaf1f9b99fc4b54a21c72847ff/scripts/microxrceddsgen.in#L7

Looking at these, it seems the point of printing the version is actually to get an exit code for later logic based on if the script exists. 

Since the intent is to check whether the program exists, the following is a recommended solution:
https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script

Let me know if you like the new approach. I think a similar one can be taken on the `.bat` file.

**Comment by pablogs9** [comment]
I like this approach of checking if `java` command is available.

**Comment by Ryanf55** [comment]
Ok. I'll try the same out for windows. I will need you to test since I don't have a windows dev platform.

**Comment by Ryanf55** [comment]
Can you please review this? We're still getting terminal span from builds, and the devs don't like it.

**Comment by pablogs9** [comment]
Did you test this on windows? I do not have a windows dev platform.

**Comment by Ryanf55** [comment]
Nope. If we don't have any windows platforms, what about reverting the windows change and we can just merge Linux?

**Comment by pablogs9** [comment]
Sure

**Comment by Ryanf55** [comment]
HI Pablo, I dropped the windows commit. Please take another review. We are continuing to have users report problems during installation due to the stderr of this package.

**Comment by pablogs9** [comment]
You have added a bunch of commits from my `feature/v3`. Could you keep this with the last commit only?

**Comment by Ryanf55** [comment]
> You have added a bunch of commits from my `feature/v3`. Could you keep this with the last commit only?

Done. Sorry, this PR was branched off of `Ardupilot` master, which includes some stuff from feature/v3 we're using. It's clean now.

**Review by pablogs9 — APPROVED** [review]

**Pull request merged**
